spring:
  application:
    name: InsideTrackTestGChiappe
  data:
    arangodb:
      hosts: 10.1.0.101

server:
  port: 9000

info:
  app:
    name: InsideTrack's Test for Giancarlo Chiappe
    version: @version@
    api-type: GraphQL
    java-home: ${JAVA_HOME:'Not Defined.'}

altair:
  enabled: true
  cdn:
    enabled: true
  static:
    base-path: /
  endpoint:
    graphql: /graphql

graphql:
  tools:
    schema-location-pattern: 'schema/*.graphqls'
  servlet:
    mapping: /graphql